# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 16:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('patronymic', models.CharField(max_length=64, verbose_name='patronymic')),
            ],
        ),
        migrations.CreateModel(
            name='BirthEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='issued by organisation')),
            ],
        ),
        migrations.CreateModel(
            name='BirthNoteLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(max_length=255, verbose_name='law')),
            ],
        ),
        migrations.CreateModel(
            name='BirthPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45, verbose_name='country')),
                ('region', models.CharField(max_length=64, verbose_name='region')),
                ('district', models.CharField(max_length=64, verbose_name='district')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='DeathEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('number', models.CharField(max_length=32, verbose_name='number')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('issuer', models.CharField(max_length=255, verbose_name='issuer')),
                ('additional_info', models.TextField(blank=True, verbose_name='additional info')),
            ],
        ),
        migrations.CreateModel(
            name='DeathPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45, verbose_name='country')),
                ('region', models.CharField(max_length=45, verbose_name='region')),
                ('district', models.CharField(max_length=45, verbose_name='district')),
                ('city', models.CharField(max_length=45, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='issue date')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='note creation time')),
                ('compose_date', models.DateField(blank=True, verbose_name='note record compose time')),
                ('was_restored', models.BooleanField(default=False, verbose_name='was restored')),
                ('official_info', models.CharField(max_length=255, verbose_name='')),
                ('status', models.CharField(max_length=45)),
                ('notes', models.TextField(blank=True)),
                ('language', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_service', models.BooleanField(verbose_name='military service')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.PositiveIntegerField(verbose_name='postal code')),
                ('country', models.CharField(max_length=45, verbose_name='country')),
                ('region', models.CharField(max_length=64, verbose_name='region')),
                ('district', models.CharField(max_length=64, verbose_name='district')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('street', models.CharField(max_length=64, verbose_name='street')),
                ('house', models.CharField(max_length=45, verbose_name='house')),
                ('room', models.CharField(blank=True, max_length=45, verbose_name='room')),
            ],
        ),
        migrations.CreateModel(
            name='BirthNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vital_records.Note')),
                ('military_service', models.BooleanField(verbose_name='military service')),
            ],
            bases=('vital_records.note',),
        ),
        migrations.CreateModel(
            name='DeathNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vital_records.Note')),
                ('date_of_death', models.DateField(verbose_name='date of death')),
                ('death_reason', models.TextField(blank=True, verbose_name='reason of death')),
                ('rehabilitation_statements', models.CharField(max_length=45, verbose_name='rehabilitation statements')),
                ('death_evidence', models.ManyToManyField(to='vital_records.DeathEvidence')),
                ('death_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.DeathPlace')),
                ('discarded_documents', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Person')),
            ],
            bases=('vital_records.note',),
        ),
        migrations.CreateModel(
            name='MarriageNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vital_records.Note')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Person')),
            ],
            bases=('vital_records.note',),
        ),
        migrations.AddField(
            model_name='registrar',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Residence'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Registrar'),
        ),
        migrations.AddField(
            model_name='applicantinfo',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Residence'),
        ),
        migrations.AddField(
            model_name='registryuser',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vital_records.Registrar'),
        ),
        migrations.AddField(
            model_name='registryuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
