# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital_records', '0002_birthnote_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantinfo',
            options={'verbose_name': 'Applicant information', 'verbose_name_plural': 'Applicants information'},
        ),
        migrations.AlterModelOptions(
            name='birthevidence',
            options={'verbose_name': 'Birth evidence', 'verbose_name_plural': 'Birth evidences'},
        ),
        migrations.AlterModelOptions(
            name='birthnote',
            options={'verbose_name': 'Birth note record', 'verbose_name_plural': 'Birth note records'},
        ),
        migrations.AlterModelOptions(
            name='birthnotelaw',
            options={'verbose_name': 'Birth related law', 'verbose_name_plural': 'Birth related laws'},
        ),
        migrations.AlterModelOptions(
            name='birthplace',
            options={'verbose_name': 'Birth place', 'verbose_name_plural': 'Birth places'},
        ),
        migrations.AlterModelOptions(
            name='deathevidence',
            options={'verbose_name': 'Death evidence', 'verbose_name_plural': 'Death evidences'},
        ),
        migrations.AlterModelOptions(
            name='deathnote',
            options={'verbose_name': 'Death note record', 'verbose_name_plural': 'Death note records'},
        ),
        migrations.AlterModelOptions(
            name='deathplace',
            options={'verbose_name': 'Death place', 'verbose_name_plural': 'Death places'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='marriagenote',
            options={'verbose_name': 'Marriage note record', 'verbose_name_plural': 'Marriage note records'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='registrar',
            options={'verbose_name': 'Registrar', 'verbose_name_plural': 'Registrars'},
        ),
        migrations.AlterModelOptions(
            name='residence',
            options={'verbose_name': 'Residence info', 'verbose_name_plural': 'Residences'},
        ),
        migrations.AddField(
            model_name='deathnote',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vital_records.ApplicantInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deathnote',
            name='discarded_documents',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vital_records.Document'),
        ),
    ]
