# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_records', '0004_auto_20160429_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthnote',
            name='military_service',
        ),
        migrations.AddField(
            model_name='deathnote',
            name='note_number',
            field=models.PositiveIntegerField(default=0, verbose_name='note number'),
            preserve_default=False,
        ),
    ]
